import { AnimatePresence, motion } from 'framer-motion';
import { Compass, X } from 'lucide-react';
import type { Explanation } from '../types';
import { EmptyState } from './EmptyState';

interface ExplanationPanelProps {
  explanation: Explanation | null;
  open: boolean;
  onClose: () => void;
}

export function ExplanationPanel({ explanation, open, onClose }: ExplanationPanelProps) {
  return (
    <AnimatePresence>
      {open && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.18 }}
            onClick={onClose}
            className="fixed inset-0 z-40 bg-page/70 backdrop-blur-sm"
          />
          <motion.aside
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'spring', stiffness: 380, damping: 38 }}
            className="fixed right-0 top-0 z-50 flex h-full w-full max-w-md flex-col border-l border-border bg-panel"
          >
            <div className="flex items-center justify-between border-b border-border px-5 py-4">
              <span className="label-caps inline-flex items-center gap-2">
                <Compass size={13} strokeWidth={2} className="text-accent" />
                Why this decision
              </span>
              <button
                type="button"
                onClick={onClose}
                aria-label="Close"
                className="flex h-7 w-7 items-center justify-center rounded-full text-text-secondary transition-colors duration-150 hover:bg-border/60 hover:text-text-primary"
              >
                <X size={14} strokeWidth={2} />
              </button>
            </div>

            <div className="no-scrollbar flex-1 overflow-y-auto px-5 py-5">
              {!explanation ? (
                <EmptyState text="No explanation available for this decision." />
              ) : (
                <div className="flex flex-col gap-6">
                  <h2 className="text-lg font-semibold leading-snug text-text-primary">
                    {explanation.headline}
                  </h2>

                  <p className="voice-narrative text-[15px] leading-relaxed text-text-secondary">
                    {explanation.narrative}
                  </p>

                  <div>
                    <span className="label-caps">Key assumptions</span>
                    <ul className="mt-2 flex flex-col gap-1.5">
                      {explanation.key_assumptions.map((a) => (
                        <li key={a} className="flex gap-2 text-sm text-text-secondary">
                          <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-text-muted" />
                          {a}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <span className="label-caps">Trade-offs accepted</span>
                    <ul className="mt-2 flex flex-col gap-1.5">
                      {explanation.tradeoffs.map((t) => (
                        <li key={t} className="flex gap-2 text-sm text-text-secondary">
                          <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-warning" />
                          {t}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="rounded-lg border-l-2 border-accent bg-accent-dim/20 px-4 py-3.5">
                    <span className="label-caps text-accent">Would change if…</span>
                    <ul className="mt-2 flex flex-col gap-2">
                      {explanation.would_change_if.map((w) => (
                        <li key={w} className="text-sm leading-snug text-text-primary">
                          {w}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <span className="font-mono text-[10.5px] tabular-nums text-text-muted">
                    generated by {explanation.generated_by} · grounded in{' '}
                    {explanation.grounded_fields.length} fields from the decision object
                  </span>
                </div>
              )}
            </div>
          </motion.aside>
        </>
      )}
    </AnimatePresence>
  );
}
